function [Ip] = mosaic(image1, image2,X1,X2,Y1,Y2,num)
I1 = double(imread(image1));
[h1 w1 d1] = size(I1);
I2 = double(imread(image2));
[h2 w2 d2] = size(I2);
Z  = [ X2'  Y2'; Y2' -X2';ones(1,num) zeros(1,num);zeros(1,num) ones(1,num)]';	 
xp = [ X1 ; Y1 ];
t  = Z \ xp;
a  = t(1); 
b  = t(2);
tx = t(3);
ty = t(4);
T = [a b tx; -b a ty; 0 0 1];
cp = T*[ 1 1 w2 w2; 1 h2 1 h2; 1 1 1 1 ]; 
Xpr = min( [ cp(1,:) 0 ] ) : max( [cp(1,:) w1] ); 
Ypr = min( [ cp(2,:) 0 ] ) : max( [cp(2,:) h1] );
[Xp,Yp] = ndgrid(Xpr,Ypr);
[wp hp] = size(Xp); 
X = T \ [ Xp(:) Yp(:) ones(wp*hp,1) ]';  
clear Ip;
xI = reshape( X(1,:),wp,hp)';
yI = reshape( X(2,:),wp,hp)';
Ip(:,:,1) = interp2(I2(:,:,1), xI, yI, '*bilinear');
Ip(:,:,2) = interp2(I2(:,:,2), xI, yI, '*bilinear'); 
Ip(:,:,3) = interp2(I2(:,:,3), xI, yI, '*bilinear'); 
offset =  -round( [ min( [ cp(1,:) 0 ] ) min( [ cp(2,:) 0 ] ) ] );
Ip(1+offset(2):h1+offset(2),1+offset(1):w1+offset(1),:) = double(I1(1:h1,1:w1,:));
figure;
sift_image = Ip / 255;
image(sift_image);
axis image;
imwrite(sift_image, 'Sift_Result.jpg');